### ISSUE TITLE
[Tutum] add more robust websocket event stream handling

### ISSUE THREAD

**Issue by jshimko** [reactioncommerce/launchdock#11]
The persistent Tutum events stream connection currently listens for events that apply to stacks or services that already exist in the Launchdock database.  Ideally, this should handle _all_ events so that you could manage Tutum from anywhere and Launchdock would always stay in sync.  This shouldn't be too difficult, but it will definitely require several additional Tutum API calls.  The events stream has very little info about the entities it's reporting about, so any event message for a new stack/service would need to trigger a few API calls to get the full details of the stack and each of the services within that stack.  So, likely a total of 5 API calls.  One for the stack itself and one for each of the 4 services that exist within the stack (app, mongo1, mongo2, mongo3).

**Comment by aaronjudd** [comment]
Closing - we should have no focus on Tutum (Docker cloud) for now.
