### ISSUE TITLE
Restrict Automated or duplicate site creations

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/launchdock#13]
The signup form, and the related methods should ensure that duplicate, repeated entries aren't processed.  We'll probably need to monitor this for a bit to figure out the best logic. I think it could be 1 submission every 5 mins per IP, or something like that.

**Comment by jshimko** [comment]
I think the easiest approach for this for now is going to be to require email verification before you can launch a stack (we already implement this with beta invitations, so it'll just be a small tweak once stack creation is unrestricted and open to the public)
