### ISSUE TITLE
Tutum Stack Limit

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/launchdock#14]

**Comment by jshimko** [comment]
Sent to Tutum's Intercom chat on Jan 1...

> Hi there. Just hit a limit on running services in our account (50). We have 4 services per stack, so we can only run 12 stacks under that limitation. We soon will be starting to launch a lot of stacks for early beta customers, so I'm wondering what our options are for having that limit removed. Thanks!

Then sent this follow-up today (Jan 6)...
> ?

Unfortunately, still no answer.

**Comment by aaronjudd** [comment]
Closing, as we're supporting Rancher now instead of Tutum any more as a primary (because of stuff like this).
