### ISSUE TITLE
rancher integration package

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/launchdock#16]
Issue to track progress of a integration package for Rancher that duplicates the functionality of the Tutum package.

**Comment by jshimko** [comment]
FYI, the beginnings of this are here:

https://github.com/reactioncommerce/launchdock/tree/master/packages/launchdock-rancher

**Comment by aaronjudd** [comment]
@jshimko status update?

**Comment by jshimko** [comment]
Stack creation/deletion and SSL management are all deployed and this package now does everything that the Tutum package did.  

This package will be a WIP for quite a while as we work out what things we need LD to manage on the Rancher side (app upgrades, Mongo management, etc.), so I'm going to close this for now in favor of some more specific issues for features related to Rancher integration.
