### ISSUE TITLE
LD2 Documentation

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/launchdock#17]
Add installation and maintenance oriented documentation to the README.md

**Comment by jshimko** [comment]
The beginnings of this have been [committed](https://github.com/reactioncommerce/launchdock/commit/fb82dee104e7dc00c12b47276e1d070a3c334fdd).  Probably going to hold off on writing too much more until I finish replacing Tutum with Rancher though.  For now, the key setup info is there.  Just needs a little more detail on usage and remote API.

**Comment by aaronjudd** [comment]
great start though!
